### ISSUE TITLE
最新beta.50已经不兼容了

### ISSUE THREAD

**Issue by wellfrog16** [gavinliu6/vuepress-theme-mix#12]
![image](https://user-images.githubusercontent.com/22096815/187061934-543c90c9-fefe-455e-bc89-6e7095ec1caa.png)

**Comment by wellfrog16** [comment]
另外我发现主题包里的package里依赖有两个
```
"@vuepress/plugin-external-link-icon": "^2.0.0-beta.49",
 "@vuepress/plugin-git": "^2.0.0-beta.49",
```

前面多了^，导致即使指定了2.0.0-beta.49版本，也会把vuepress各个依赖安装成 2.0.0-beta.50
目前重新下载安装已经无法使用了，也无法继续使用2.0.0-beta.49版本

**Comment by gavinliu6** [comment]
谢谢反馈，下个版本会修复。

**Comment by ysredcity** [comment]
什么时候能兼容新版本啊

**Comment by gavinliu6** [comment]
抱歉！过年回家太忙了，刚返岗，争取下周更新哈^-^

**Comment by gavinliu6** [comment]
抱歉！由于本主题落后了 VuePress 太多版本，要兼容最新版本需要做的变动工作超出了预期，再加上本人能力和精力有限，暂不打算近期更新……

**Comment by gavinliu6** [comment]
新的 2.x 已经发布。
