### ISSUE TITLE
右边侧边栏可以单独抽出来放到v2版本的默认主题中吗

### ISSUE THREAD

**Issue by Mankvis** [gavinliu6/vuepress-theme-mix#13]
右边侧边栏可以单独抽出来放到v2版本的默认主题中吗，盼复

**Comment by gavinliu6** [comment]
不好意思，我没明白你意思，可以再详细描述下吗？

**Comment by Mankvis** [comment]
![image](https://user-images.githubusercontent.com/49258868/190841532-41174a59-9247-4dfb-94ad-27f1d2a3051f.png)
这一块默认主题中好像是不支持的，这块能单独拆出来放到默认主题中吗

**Comment by gavinliu6** [comment]
(⊙o⊙)…额，默认主题是 VuePress 官方维护的，本主题（Mix）的侧边悬浮 TOC 是嵌在主题内置的，不能拆出来用于官方的默认主题。我想你大概是需要一个支持悬浮 TOC 的插件吧。

**Comment by Mankvis** [comment]
> (⊙o⊙)…额，默认主题是 VuePress 官方维护的，本主题（Mix）的侧边悬浮 TOC 是嵌在主题内置的，不能拆出来用于官方的默认主题。我想你大概是需要一个支持悬浮 TOC 的插件吧。

对的

**Comment by gavinliu6** [comment]
你可以去社区找下看，或者参照本主题的源码自己做一个的。

**Comment by Mankvis** [comment]
> 你可以去社区找下看，或者参照本主题的源码自己做一个的。

嗯，好的，谢谢
