### ISSUE TITLE
转让仓库

### ISSUE THREAD

**Issue by gavinliu6** [gavinliu6/vuepress-theme-mix#16]
由于本人精力有限，无暇维护该仓库，现寻求有意接手者，连带 npm 代码包一起转让。

**Comment by Mister-Hope** [comment]
Hi, this is Mr.Hope from VuePress team, I can give basic maintain for this repo.

You can invite me in both GitHub and npm, both can be done with `mister-hope@outlook.com`

**Comment by gavinliu6** [comment]
Greatly appreciated.  I've invited you in the both.

**Comment by Mister-Hope** [comment]
I have some work with ecosystem and my theme, when everything is finished, I will try to update this repo to make it compatible with latest vuepress2 rc version
