### ISSUE TITLE
修改代码块样式

### ISSUE THREAD

**Issue by LwRuan** [gavinliu6/vuepress-theme-mix#2]
![image](https://user-images.githubusercontent.com/61261306/137888484-4c42f48b-e5ec-48c7-b3f0-c79ea473d51c.png)
我想去掉这个代码块上面的三个点并且修改scrollbar的默认样式，可以在项目里直接修改吗？

**Comment by gavinliu6** [comment]
你好，代码块左上角的三个装饰点是模仿的 macOS 应用窗口，像代码图片生成器 [Carbon](https://carbon.now.sh/) 也使用了这个风格。个人觉得看起来还是挺漂亮的，所以本主题仍会坚持使用之。但是，你可以在你自己项目的 `.vuepress/styles/index.scss` 文件中自定义该样式。

至于 scrollbar 的默认样式，除了在 `.vuepress/styles/index.scss` 自定义外，你也可以通过提交 PR 提交你的想法。

**Comment by LwRuan** [comment]
好的，谢谢
