### ISSUE TITLE
Collapsible

### ISSUE THREAD

**Issue by daniel-farina** [gavinliu6/vuepress-theme-mix#3]
Hello, 

```
 collapsible: true
```

Is great but is there an option to make it collapsed as default, for example: collapsed = true

**Comment by gavinliu6** [comment]
Not for now. But I will add it in the next release. If possible, `collapsible` and upcoming `collapsed ` will be available for every sidebar group.

**Comment by gavinliu6** [comment]
`collapsed` has been supported.
