### ISSUE TITLE
可否把 alt 属性同时也包含进图片链接里

### ISSUE THREAD

**Issue by Tikas** [gavinliu6/vuepress-theme-mix#6]
最近发现 seo 报告里，一堆的图片 alt 属性是空的，仔细查看一下，其实 alt 属性是拆出换行显示出来，对这个还是非常满意的。

然而，不知道是否影响到图片的 alt 描述，不知能否在图片链接里 alt 属性同时也赋予。

**Comment by gavinliu6** [comment]
没太明白你描述的“其实 alt 属性是拆出换行显示出来”。

你是想让 `<img />` 标签的 `alt` 属性不为空是吧，比如 `![img desc](img_path)` 渲染成 `<img alt="img desc" src="img_path">`？

**Comment by gavinliu6** [comment]
好的，没问题，下次更新给带上。

**Comment by Tikas** [comment]
非常感谢，对 seo 比较友好的改进都是值得的，元宵快乐

**Comment by gavinliu6** [comment]
你好，我看了下代码，本主题使用了 https://github.com/arve0/markdown-it-implicit-figures 来实现图片的说明文字展示，目前 figcaption 和 img 的 alt 属性只能选择其一，你可以通过主题提供的 [figcaption](https://vuepress-theme-mix.vercel.app/configuration/markdown.html#figcaption) 配置项来禁用 figcaption，从而使 alt 属性有值。具体可以参考 https://github.com/arve0/markdown-it-implicit-figures 。
