### ISSUE TITLE
优化滚动条显示样式，让多目录显示更友好

### ISSUE THREAD

**Issue by Tikas** [gavinliu6/vuepress-theme-mix#7]
作者大大：

您好，今天我在撰写一篇文章时，由于次级标题很多，导致侧边目录长度超过屏幕高度，会显示出滚动条出来。

在 PC 端下使用夜间模式时，显示非常不友好。

在手机端，由于手机操作系统的默认滚动条样式细小，显示非常友好。

不知道，可否方便在 PC 端增加：下拉滚动条样式。

[示例地址](https://xtikas.com/legion.html)

**Comment by gavinliu6** [comment]
好的，在下次更新时，我自定义一下滚动条样式。

**Comment by gavinliu6** [comment]
抱歉这么久才解决你的问题，自定义滚动条（侧边栏和页内 TOC）已随新版本发布。

> 滚动条组件移植自 [Naive UI 组件库](https://github.com/TuSimple/naive-ui)
