### ISSUE TITLE
Alignment issue of the code block.

### ISSUE THREAD

**Issue by Hsins** [gavinliu6/vuepress-theme-mix#8]
In the code block, the line number and the code line are not on the same base lines. Take [VuePress Mix Theme Documentation](https://vuepress-theme-mix.vercel.app/guide/writing-content.html#code-blocks) for example:

![image](https://user-images.githubusercontent.com/26391143/155841259-255ade67-d850-4e1f-9af7-521168f8c8d6.png)

Moreover, there're something issue with the scroll bar but not mentioned in issue https://github.com/gavinliu6/vuepress-theme-mix/issues/7:

| Width: `483 px` | Width: `550 px` |
| :--: | :--: |
| ![image](https://user-images.githubusercontent.com/26391143/155841331-83cda790-c725-4ce8-9b00-4f67eb1a64e8.png) | ![image](https://user-images.githubusercontent.com/26391143/155841336-7e03a4f4-8fdf-43a5-ada1-174fdb4af6a4.png) |

By the way, [Mix Theme](https://github.com/gavinliu6/vuepress-theme-mix) is one of the best theme for VuePress 2 I have ever used. Thanks for your work :) ❤️

**Comment by gavinliu6** [comment]
Thank you for your approval of the theme. I will solve these two issues in the next release.

**Comment by gavinliu6** [comment]
I find it's fine on my MacBook, could you tell me what device and brower you are using?

**Comment by Hsins** [comment]
Hi @gavinliu6,

I'm using **Microsoft Edge** and **Google Chrome** on **Microsoft Windows 11** platform. It seems that add `line-height: 1.41` to `<pre></pre>` element work fine on my side. It's weird because the `<div class="line-numbers">` element use `line-height: 1.4`...

**Comment by gavinliu6** [comment]
I forgot to add the following styles:

```css
.line-number {
    line-height: 0;
}
```

PS: I don't have a solution yet for the horizontal scrollbar of the code block, now it remain as it was.
